package com.zai.booking.entity;

import lombok.Data;
import java.util.Date;
import java.math.BigDecimal;
import java.util.List;

@Data
public class Booking {
    private String bookingId;
    private String chainId;
    private String hotelId;
    private String chainCode;
    private String chainName;
    private String hotelCode;
    private String hotelName;
    private String roomTypeCode;
    private String roomTypeName;
    private String rateCode;
    private String rateCodeName;
    private String packageCode;
    private String packageName;
    private String channelCode;
    private String channelSubcode;
    private String bookerCode;
    private String agentCode;
    private String sourceCode;
    private String marketCode;
    private String bookerType;
    private String channelResvNo;
    private String channelResvSno;
    private String channelResvPno;
    private String crsResvNo;
    private String crsResvPno;
    private String crsResvCheckinNo;
    private String agentResvNo;
    private String agentResvPno;
    private String hotelResvNo;
    private String hotelResvKey;
    private String hotelResvConfirm;
    private String hotelRoomNo;
    private String paymentType;
    private String reservationType;
    private String cancellationType;
    private Integer latestCancellationDays;
    private String latestCancellationTime;
    private Boolean cancellableAfterBooking;
    private String orderRetentionTime;
    private String arrivalTime;
    private String remarkHotel;
    private String remarkChannel;
    private String remarkAgent;
    private String remarkGuest;
    private String remarkSpecial;
    private String remarkInvoice;
    private String remarkCancel;
    private String companyId;
    private String companyNo;
    private String companyName;
    private String companyTmcId;
    private String companyTmcNo;
    private String companyTmcName;
    private String memberNoGuest;
    private String memberTypeGuest;
    private String memberNoBooker;
    private String memberTypeBooker;
    private String guestId;
    private String guestName;
    private String guestEname;
    private String bookerId;
    private String bookerName;
    private Date bookingDate;
    private BigDecimal advanceBookingDays;
    private Date checkInDate;
    private Date checkOutDate;
    private Integer stayDays;
    private Date checkInDateActual;
    private Date checkOutDateActual;
    private Integer stayDaysActual;
    private Integer totalRooms;
    private Integer totalRoomsActual;
    private Integer totalRoomNights;
    private Integer totalRoomNightsActual;
    private Integer totalGuests;
    private Integer totalGuestsActual;
    private String bookingType;
    private String bookingStatusChannel;
    private String bookingStatusHotel;
    private String bookingStatusAgent;
    private BigDecimal depositAmountChannel;
    private BigDecimal depositAmountAgent;
    private BigDecimal depositAmountHotel;
    private BigDecimal penaltyAmountChannel;
    private BigDecimal penaltyAmountHotel;
    private BigDecimal penaltyAmountAgent;
    private BigDecimal totalPriceChannel;
    private BigDecimal totalPriceHotel;
    private BigDecimal totalPriceAgent;
    private BigDecimal totalPriceChannelActual;
    private BigDecimal totalPriceHotelActual;
    private BigDecimal totalPriceAgentActual;
    private Date paymentDate;
    private String paymentNo;
    private Date billDate;
    private String billNo;
    private BigDecimal cateringFeeHotel;
    private BigDecimal banquetFeeHotel;
    private BigDecimal otherFeeHotel;
    private BigDecimal totalRevenueFeeHotel;
    private Integer sign;
    
    // 销售层级信息
    private String salesLevelAId;
    private String salesLevelAPhone;
    private String salesLevelAEmail;
    private String salesLevelAName;
    private String salesLevelBId;
    private String salesLevelBPhone;
    private String salesLevelBEmail;
    private String salesLevelBName;
    private String salesLevelCId;
    private String salesLevelCPhone;
    private String salesLevelCEmail;
    private String salesLevelCName;
    
    // 预订每日价格信息列表
    private List<BookingDaily> bookingDailys;
    
    private Date createdAt;
    private Date updatedAt;
} 