CREATE TABLE hotel (
  hotel_group_id bigint NOT NULL,
  id bigint NOT NULL,
  ids bigint NOT NULL,
  code varchar(30) NOT NULL,
  sta char(10) NOT NULL DEFAULT '0',
  audit char(10) NOT NULL DEFAULT '0',
  descript varchar(200) NOT NULL,
  descript_en varchar(200) NOT NULL DEFAULT '',
  descript_short varchar(50),
  country varchar(20) NOT NULL,
  city varchar(100) NOT NULL DEFAULT '',
  address1 varchar(500) NOT NULL DEFAULT '',
  address2 varchar(500) NOT NULL DEFAULT '',
  phone varchar(50) NOT NULL DEFAULT '',
  fax varchar(50) NOT NULL DEFAULT '',
  phone_rsv varchar(50),
  website varchar(200),
  email varchar(70) NOT NULL DEFAULT '',
  dns varchar(70),
  remark text,
  logo text,
  photo varchar(400),
  html_info varchar(400),
  list_order int NOT NULL DEFAULT 0,
  create_user varchar(30) NOT NULL,
  create_datetime timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modify_user varchar(30) NOT NULL,
  modify_datetime timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  province_code varchar(50),
  city_code varchar(50),
  district_code varchar(50),
  town_code varchar(50),
  shopping_district_code varchar(50),
  scenic_spot_code varchar(50),
  book_list_order varchar(50),
  start_level_code varchar(50),
  brand_code varchar(50),
  score varchar(10) DEFAULT '5.0',
  category_code varchar(20),
  manage_type varchar(20) DEFAULT '',
  map_html text,
  pair_pic varchar(400),
  app_type varchar(30) DEFAULT '',
  client_type varchar(20) DEFAULT '',
  client_version varchar(20),
  area1 varchar(30),
  area2 varchar(30),
  online_check char(10) DEFAULT 'T',
  server_name varchar(200),
  report_server_name varchar(500) DEFAULT '',
  open_date timestamp(3),
  close_date timestamp(3),
  trial_date timestamp(3),
  upload_datetime timestamp(3) NOT NULL
);
