CREATE TABLE master_guest (
  hotel_group_id bigint NOT NULL,
  hotel_id bigint NOT NULL,
  ids bigint NOT NULL,
  id bigint NOT NULL,
  profile_type varchar(40) NOT NULL,
  profile_id bigint NOT NULL,
  times_in int DEFAULT 0,
  name varchar(90) NOT NULL,
  last_name varchar(70) NOT NULL DEFAULT '',
  first_name varchar(60) NOT NULL DEFAULT '',
  name2 varchar(80) NOT NULL DEFAULT '',
  name3 varchar(80) NOT NULL DEFAULT '',
  name_combine varchar(500) NOT NULL,
  sex varchar(10) NOT NULL DEFAULT '',
  language varchar(50) NOT NULL DEFAULT '',
  title varchar(50) NOT NULL,
  salutation varchar(100) NOT NULL,
  interest varchar(500) DEFAULT '',
  birth timestamp(3),
  race varchar(40) NOT NULL,
  religion varchar(40) NOT NULL,
  career varchar(80) NOT NULL,
  occupation varchar(80) NOT NULL,
  nation varchar(80) NOT NULL,
  country varchar(80) NOT NULL,
  state varchar(40) NOT NULL,
  city varchar(80),
  division varchar(30) NOT NULL,
  street text,
  zipcode varchar(40),
  vip varchar(50) DEFAULT '0',
  phone varchar(500) DEFAULT '',
  mobile varchar(500) DEFAULT '',
  fax varchar(50) DEFAULT '',
  email varchar(90) DEFAULT '',
  id_code varchar(100) NOT NULL,
  id_no varchar(200) NOT NULL,
  id_end timestamp(3),
  visa_type varchar(40),
  visa_no varchar(60),
  visa_begin timestamp(3),
  visa_end timestamp(3),
  visa_grant varchar(40),
  enter_port varchar(40),
  enter_date timestamp(3),
  enter_date_end timestamp(3),
  photo_pic bigint,
  photo_sign bigint,
  remark text DEFAULT '',
  room_prefer varchar(90) DEFAULT '',
  feature text,
  plate_no varchar(60) DEFAULT '',
  create_user varchar(60) NOT NULL,
  create_datetime timestamp(3) NOT NULL,
  member_card_no varchar(80),
  modify_user varchar(60) NOT NULL,
  modify_datetime timestamp(3) NOT NULL,
  police_id varchar(100) DEFAULT '',
  upload_datetime timestamp(3) NOT NULL
);
